### ISSUE TITLE
The issue of stats.so and libRlapack.so

### ISSUE THREAD

**Issue by zqsha** [Joker-Jerome/UTMOST#9]
Hi,

Thank you for developing such an amazing toolbox. Recently, I've been running UTMOST.  When I ran joint_GBJ_test.py with the example. It reported some errors. Most of the errors are related to the stats.so and libRlapack.so. First, I have installed all the packages mentioned online. And I ran single_tissue_association_test.py successfully. 

All the errors reported are shown below,
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error: package or namespace load failed for 'stats' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/shared/apps/R/R-3.5.2/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: During startup - 
  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Warning message:

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: package 'stats' in options("defaultPackages") was not found 

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error: package or namespace load failed for 'GBJ' in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/shared/apps/R/R-3.5.2/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/shared/apps/R/R-3.5.2/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Installing package into '/home/zhisha/R/x86_64-pc-linux-gnu-library/3.5'
(as 'lib' is unspecified)

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: trying URL 'https://cloud.r-project.org/src/contrib/GBJ_0.5.2.tar.gz'

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: Content type 'application/x-gzip'
  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning:  length 48718 bytes (47 KB)

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: =
  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 

  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: downloaded 47 KB

  warnings.warn(x, RRuntimeWarning)
* installing *source* package 'GBJ' ...
** package 'GBJ' successfully unpacked and MD5 sums checked
** libs
g++ -std=gnu++11 -I"/usr/shared/apps/R/R-3.5.2/lib64/R/include" -DNDEBUG  -I"/usr/shared/apps/R/R-3.5.2/lib64/R/library/Rcpp/include" -I"/home/zhisha/R/x86_64-pc-linux-gnu-library/3.5/BH/include" -I/usr/local/include   -fpic  -g -O2 -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/shared/apps/R/R-3.5.2/lib64/R/include" -DNDEBUG  -I"/usr/shared/apps/R/R-3.5.2/lib64/R/library/Rcpp/include" -I"/home/zhisha/R/x86_64-pc-linux-gnu-library/3.5/BH/include" -I/usr/local/include   -fpic  -g -O2 -c ebb_crossprob_cor_R.cpp -o ebb_crossprob_cor_R.o
g++ -std=gnu++11 -shared -L/usr/shared/apps/R/R-3.5.2/lib64/R/lib -L/usr/local/lib64 -o GBJ.so RcppExports.o ebb_crossprob_cor_R.o -L/usr/shared/apps/R/R-3.5.2/lib64/R/lib -lR
installing to /home/zhisha/R/x86_64-pc-linux-gnu-library/3.5/GBJ/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (GBJ)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: 
  warnings.warn(x, RRuntimeWarning)
/home/zhisha/.local/lib/python2.7/site-packages/rpy2/rinterface/__init__.py:186: RRuntimeWarning: The downloaded source packages are in
        '/tmp/Rtmpmbwg9d/downloaded_packages'
  warnings.warn(x, RRuntimeWarning)
Traceback (most recent call last):
  File "joint_GBJ_test.py", line 373, in <module>
    run(args)
  File "joint_GBJ_test.py", line 120, in run
    r_requirement()
  File "joint_GBJ_test.py", line 66, in r_requirement
    importr_try("GBJ")
  File "joint_GBJ_test.py", line 81, in importr_try
    rpack = importr(pkgname)
  File "/home/zhisha/.local/lib/python2.7/site-packages/rpy2/robjects/packages.py", line 453, in importr
    env = _get_namespace(rname)
rpy2.rinterface.RRuntimeError: Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/shared/apps/R/R-3.5.2/lib64/R/library/stats/libs/stats.so':
  libRlapack.so: cannot open shared object file: No such file or directory

I often use linux server to run these analyses. So, I installed the R packages and Python packages in the local folder, such as \R\x86_64-pc-linux-gnu-library\3.5. In this folder, there is no other folders except for packages here. I know in the typical structure of R, there are several folders in R, such as lib, bin, library, which are on the server, but not in my local folder. I guess that is why the python command cannot find the libRlapack.so. Because this command would search the libRlapack.so based on the pathname of my R packages. However, there are only packages in my local folder. So, it could not find out the lib or library folder or libRlapack.so.

Do you have any suggestions? Thank you so much.

Best,
Zhiqiang

**Comment by duaghk** [comment]
How about install libblas-dev?

**Comment by zqsha** [comment]
Thank you so much. It works now. I found in the UTMOST/intermediate/gene_info.txt, there are 17290 genes. But, when I got the results from the joint_GBJ_test. I found, for some genes, there is no p or t values. Does that mean I could exclude these genes when I calculate the number of total genes for Bonferroni correction? For example, I just got 16000 genes with T and P values, then I could use 0.05/16000 as p-value for correction? Thanks again.

Best,
Zhiqiang

**Comment by Joker-Jerome** [comment]
Thanks! The NA results might indicate that we don't have imputation models for the selected tissues. As for the test, I think that's a pure multiple testing problem. Therefore the total number should be consistent with the number of total genes from previous single tissue tests, which is the number of joint tests you performed.

**Comment by zqsha** [comment]
OK. I see. Thanks for clearing it up. When I check the results, I found some genes with higher T values (e.g. 13.4), but the corresponding p values are very big (e.g. 0.02). In contrast, some genes with smaller T values (e.g. 4.5), the corresponding p values are relatively small (e.g. 0.005). Could you help me to explain it? Thanks.
